version: '3'
services:
  quack:
    image: greatbit/quack
    ports:
      - "80:80"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: greatbit/quack-mongo-demo
    ports:
      - "27017:27017"
