version: '2'
services:
  quack:
    image: greatbit/quack
    ports:
      - "80:80"
    links:
      - mongod
    depends_on:
      - mongod

  mongod:
    container_name: "mongod"
    image: mongo
    ports:
      - "27017:27017"
